name: Merge-Changes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test

      - name: Upload build to artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
#      - name: Upload test results
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-results
#          path: app/build/test-results/testDebugUnitTest
#        - name: Upload coverage results
#          uses: actions/upload-artifact@v2
#          with:
#            name: coverage-results
#            path: app/build/reports/jacoco/testDebugUnitTest/html
#        - name: Firebase App Distribution
#          uses: wzieba/Firebase-Distribution-Github-Action@v1
#          with:
#            appId: ${{ secrets.FIREBASE_APP_ID }}
#            token: ${{ secrets.FIREBASE_TOKEN }}
#            groups: testers
#            file: app/build/outputs/apk/debug/app-debug.apk
#            releaseNotes: |
#              Changes in this release
#              - ${{ github.event.head_commit.message }}
#            debug: true

